version: '3.8'

services:
  api:
    build: ./api-tech-challenge
    container_name: api_service
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development

  dashboard:
    build: ./dashboard
    container_name: dashboard_front
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      API_URL: http://api_service:8080

  welcome:
    build: ./welcome
    container_name: welcome_front
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
