version: '3.8'

services:
  api:
    build: ./api-tech-challenge
    container_name: api_service
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
    volumes:
      - ./api-tech-challenge:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  dashboard:
    build: ./dashboard
    container_name: dashboard_front
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development
      API_URL: http://api_service:8080
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    command: ["npx", "nodemon", "--watch", ".", "--ext", "js,json,tsx,ts", "--exec", "npm run dev"]

  welcome:
    build: ./welcome
    container_name: welcome_front
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./welcome:/app
      - /app/node_modules
    command: ["npx", "nodemon", "--watch", ".", "--ext", "js,json,tsx,ts", "--exec", "npm run dev"]
